---
# build pipeline
kind: pipeline
name: build

steps:

  # clone project on mac os buildserver
  - name: clone-ios
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - mkdir tiny_release_build_$BUILD_ID
        - cd tiny_release_build_$BUILD_ID
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/tiny_release.git tiny_release --recursive
        - cd tiny_release
        - git checkout $DRONE_COMMIT

  - name: widget-test
    image: mingc/android-build-box
    depends_on: [ clone ]
    commands:
      - flutter test

  # build when pushed on master or feature branch but not when version tagged
  - name: android-build
    image: mingc/android-build-box
    depends_on: [ clone, widget-test ]
    pub_cache:
      folder: /tmp/.pub-cache
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    commands:
      - flutter build apk --debug

  - name: ios-build
    image: appleboy/drone-ssh
    depends_on: [ clone-ios, widget-test ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 10m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_build_$BUILD_ID/tiny_release
        - bash -lc 'flock -s /Users/ci/macOS_lock flutter --version'
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flock /Users/ci/macOS_lock flutter build ios'

trigger:
  ref:
    exclude:
      - refs/tags/*
  branch:
    - master
    - feature/*

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /root/drone_rsa

# release pipeline
---
kind: pipeline
name: release

steps:
  # release only when tag starts with 'v*'
  - name: android-release
    when:
      ref:
        - refs/tags/v*
    image: mingc/android-build-box
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /drone/android_signing
    commands:
      - fastlane android release

  - name: generate-screenshots
    when:
      ref:
        - refs/tags/v*
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 60m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_testflight/tiny_release
        - bash -lc 'git checkout $DRONE_COMMIT'
        - touch /Users/ci/macOS_lock
        - bash -lc 'flock /Users/ci/macOS_lock  fastlane screenshots'

  - name: ios-release
    depends_on: [ generate-screenshots ]
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=wwul-ecvv-ewcl-gsit
        - cd tiny_release_release/tiny_release
        - git pull
        - git reset --hard
        - bash -lc 'git checkout $DRONE_COMMIT'
        - touch /Users/ci/macOS_lock
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flock /Users/ci/macOS_lock fastlane ios release'

trigger:
  ref:
    - refs/tags/v*

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /root/drone_rsa

# testflight pipeline
---
kind: pipeline
name: testflight

steps:
  # testflights only when pushed on branch 'testflights'
  - name: android-testflight
    image: mingc/android-build-box
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /drone/android_signing
    commands:
      - export BUILD_ID=${DRONE_BUILD_NUMBER}
      - fastlane android alpha

  - name: ios-testflight
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_testflight/tiny_release
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flock /Users/ci/macOS_lock fastlane ios beta'

trigger:
  branch:
    - testflight

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /root/drone_rsa

# cleanup workspace on mac build selver
---
kind: pipeline
name: cleanup-mac-buildserver

steps:
  # try to kill hanging dart processes
  - name: fix-frozen-dart
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      script:
        - killall dart ||true
        - killall flutter ||true

  - name: cleanup-build-folder
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
      script:
        - rm -rf tiny_release_build_$DRONE_BUILD_NUMBER

clone:
  disable: true

trigger:
  status:
    - success
    - failure

depends_on:
  - build
  - testflight
  - release

volumes:
  - name: drone_ssh
    host:
      path: /root/drone_rsa