---
# build pipeline
kind: pipeline
name: build

steps:

  - name: widget-test
    image: cirrusci/flutter
    depends_on: [ clone ]
    commands:
      - flutter test

  # build when pushed on master or feature branch but not when version tagged
  - name: android-build
    image: cirrusci/flutter
    depends_on: [ clone, widget-test ]
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    commands:
      - flutter packages get
      - flutter build apk --debug

trigger:
  ref:
    exclude:
      - refs/tags/*
  branch:
    - master
    - feature/*

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /srv/docker/volumes/drone_rsa

# release pipeline
---
kind: pipeline
name: release

steps:
  # release only when tag starts with 'v*'
  - name: android-release
    when:
      ref:
        - refs/tags/v*
    image: mingc/android-build-box
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /drone/android_signing
    commands:
      - fastlane android release

trigger:
  ref:
    - refs/tags/v*

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /srv/docker/volumes/drone_rsa

# testflight pipeline
---
kind: pipeline
name: testflight

steps:
  # testflights only when pushed on branch 'testflights'
  - name: android-testflight
    image: mingc/android-build-box
    environment:
      BUILD_ID: ${DRONE_BUILD_NUMBER}
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /drone/android_signing
    commands:
      - export BUILD_ID=${DRONE_BUILD_NUMBER}
      - fastlane android alpha

trigger:
  branch:
    - testflight

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /srv/docker/volumes/drone_rsa
