pipeline:
  # build when pushed on master or feature branch but not when version tagged
  android-build:
    when:
      ref:
        exclude:
          - refs/tags/*
      branch:
        - master
        - feature/*
    image: mingc/android-build-box
    group: build
    pub_cache:
      folder: /tmp/.pub-cache
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - flutter build apk --debug

  ios-build:
    when:
      ref:
        exclude:
          - refs/tags/*
      branch:
        - master
        - feature/*
    image: appleboy/drone-ssh
    group: build
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - mkdir tiny_release_build_$BUILD_ID
        - cd tiny_release_build_$BUILD_ID
        - bash -lc 'flutter --version'
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/tiny_release.git tiny_release --recursive
        - cd tiny_release
        - echo $DRONE_BRANCH
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flutter build ios'

  # release only when tag starts with 'v*'
  android-release:
    when:
      ref:
        - refs/tags/v*
    image: mingc/android-build-box
    group: release
    volumes:
      - /srv/drone/android_signing:/opt/android_signing
    pub_cache:
      folder: /tmp/.pub-cache
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - fastlane android release

  ios-release:
    when:
      ref:
        - refs/tags/v*
    image: appleboy/drone-ssh
    group: release
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - bash -lc 'flutter --version'
        - mkdir tiny_release_build_$BUILD_ID
        - cd tiny_release_build_$BUILD_ID
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/tiny_release.git tiny_release --recursive
        - cd tiny_release
        - echo $DRONE_BRANCH
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios release'

  # testflights only when pushed on branch 'testflights'
  android-testflight:
    when:
      branch:
        - testflight
    image: mingc/android-build-box
    group: testflight
    volumes:
      - /srv/drone/android_signing:/opt/android_signing
    pub_cache:
      folder: /tmp/.pub-cache
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - fastlane android alpha

  ios-testflight:
    when:
      branch:
        - testflight
    image: appleboy/drone-ssh
    group: testflight
    volumes:
      - /root/drone_rsa:/root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - bash -lc 'flutter --version'
        - mkdir tiny_release_build_$BUILD_ID
        - cd tiny_release_build_$BUILD_ID
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/tiny_release.git tiny_release --recursive
        - cd tiny_release
        - echo $DRONE_BRANCH
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios beta'

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing