pipeline:
  flutter-build:
    image: cirrusci/flutter
    pub_cache:
      folder: /tmp/.pub-cache
    commands:
      - cd /home/cirrus
      - cp -R /drone/src src
      - cd src
      - flutter build apk
