kind: pipeline
name: default

steps:

  # clone project on mac os buildserver
  - name: clone-ios
    image: appleboy/drone-ssh
    depends_on: [ clone ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - mkdir tiny_release_build_$BUILD_ID
        - cd tiny_release_build_$BUILD_ID
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/tiny_release.git tiny_release --recursive
        - cd tiny_release
        - git checkout $DRONE_COMMIT

  # build when pushed on master or feature branch but not when version tagged
  - name: android-build
    when:
      ref:
        exclude:
          - refs/tags/*
      branch:
        - master
        - feature/*
    image: mingc/android-build-box
    depends_on: [ clone ]
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - flutter build apk --debug

  - name: ios-build
    when:
      ref:
        exclude:
          - refs/tags/*
      branch:
        - master
        - feature/*
    image: appleboy/drone-ssh
    depends_on: [ clone-ios ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_build_$BUILD_ID/tiny_release
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flutter build ios'

  # release only when tag starts with 'v*'
  - name: android-release
    when:
      ref:
        - refs/tags/v*
    image: mingc/android-build-box
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /opt/android_signing
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - fastlane android release

  - name: ios-release
    when:
      ref:
        - refs/tags/v*
    image: appleboy/drone-ssh
    depends_on: [ clone, clone-ios ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_build_$BUILD_ID/tiny_release
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios release'

  # testflights only when pushed on branch 'testflights'
  - name: android-testflight
    when:
      branch:
        - testflight
    image: mingc/android-build-box
    depends_on: [ clone ]
    volumes:
      - name: android_signing
        path: /opt/android_signing
    commands:
      - export BUILD_ID=$DRONE_BUILD_NUMBER
      - fastlane android alpha

  - name: ios-testflight
    when:
      branch:
        - testflight
    image: appleboy/drone-ssh
    depends_on: [ clone-ios ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd tiny_release_build_$BUILD_ID/tiny_release
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios beta'

volumes:
  - name: android_signing
    host:
      path: /srv/drone/android_signing
  - name: drone_ssh
    host:
      path: /root/drone_rsa