
- name: android-integrationtest-28-phone
  depends_on: [ clone ]
  image: ykorzikowski/flutter-android-sdk-and-emulator:0.1.3
  privileged: true
  volumes:
    - name: kvm
      path: /dev/kvm
  environment:
    DEVICE_ID: "11"
    SYSTEM_IMAGE: "system-images;android-27;google_apis;x86"
  commands:
    - start_emulator && wait_emulator && unlock_emulator
    - flutter drive --target=test_driver/app_full.dart

---
kind: pipeline
name: integration-tests-ios

steps:
  - name: ios-integrationtest
    depends_on: [ clone ]
    image: appleboy/drone-ssh
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 10m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd paperflavor_build_$BUILD_ID/paperflavor
        - export DEV_ID=`xcrun simctl create iPhonex com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-1`
        - xcrun simctl boot $DEV_ID
        - bash -lc 'flutter drive --target=test_driver/app_full.dart -diPhonex'
        - xcrun simctl shutdown $DEV_ID
        - xcrun simctl erase $DEV_ID

volumes:
  - name: drone_ssh
    host:
      path: /root/drone_rsa

    - name: generate-screenshots
      when:
        branch:
          - testflight
      image: appleboy/drone-ssh
      depends_on: [ clone-ios ]
      volumes:
        - name: drone_ssh
          path: /root/ssh/drone_rsa
      settings:
        host: git.engineerservices.de
        port: 4222
        command_timeout: 30m
        username: ci
        key_path: /root/ssh/drone_rsa/id_rsa
        envs:
          - DRONE_BUILD_NUMBER
          - DRONE_COMMIT
          - DRONE_BRANCH
        script:
          - export BUILD_ID=$DRONE_BUILD_NUMBER
          - cd paperflavor_build_$BUILD_ID/paperflavor
          - git checkout $DRONE_COMMIT
          - bash -lc 'fastlane screenshots'

# cleanup workspace on mac build server
---
kind: pipeline
name: cleanup-mac-buildserver

steps:
  # try to kill hanging dart processes
  - name: fix-frozen-dart
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      script:
        - killall dart ||true
        - killall flutter ||true

  - name: cleanup-build-folder
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
      script:
        - rm -rf paperflavor_build_$DRONE_BUILD_NUMBER

clone:
  disable: true

trigger:
  status:
    - success
    - failure

depends_on:
  - build
  - release
  - testflight

volumes:
  - name: drone_ssh
    host:
      path: /srv/docker/volumes/drone_rsa


  - name: ios-testflight
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd paperflavor_testflight/paperflavor
        - git checkout $DRONE_COMMIT
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios beta'


  - name: ios-release
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=wwul-ecvv-ewcl-gsit
        - cd paperflavor_release/paperflavor
        - git pull
        - git reset --hard
        - bash -lc 'git checkout $DRONE_COMMIT'
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'fastlane ios release'


  - name: ios-build
    image: appleboy/drone-ssh
    depends_on: [ clone-ios, widget-test ]
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 10m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - cd paperflavor_build_$BUILD_ID/paperflavor
        - bash -lc 'flock -s /Users/ci/macOS_lock flutter --version'
        - bash -lc 'flutter --version'
        - bash -lc 'flutter packages get'
        - bash -lc 'security unlock-keychain -p 11Nase login.keychain'
        - bash -lc 'flutter build ios --debug --no-codesign'


  # clone project on mac os buildserver
  - name: clone-ios
    image: appleboy/drone-ssh
    volumes:
      - name: drone_ssh
        path: /root/ssh/drone_rsa
    settings:
      host: git.engineerservices.de
      port: 4222
      command_timeout: 15m
      username: ci
      key_path: /root/ssh/drone_rsa/id_rsa
      envs:
        - DRONE_BUILD_NUMBER
        - DRONE_COMMIT
        - DRONE_BRANCH
      script:
        - export BUILD_ID=$DRONE_BUILD_NUMBER
        - system_profiler SPSoftwareDataType
        - mkdir paperflavor_build_$BUILD_ID
        - cd paperflavor_build_$BUILD_ID
        - git clone gitea@gitea.korzikowski.de:ykorzikowski/paperflavor.git paperflavor --recursive
        - cd paperflavor
        - git checkout $DRONE_COMMIT
